#!/usr/bin/env bash
# Push the refreshed vendored data and open (or update) the upstream-sync PR.
#
# Expects to run from an actions/checkout working tree with GH_TOKEN set to a
# token that can push and open pull requests. Requires "Allow GitHub Actions
# to create and approve pull requests" enabled for the repo. Sets the step
# outputs prUrl and prId. Only runs when the sync step reported drift; the
# check below is a safety net for manual invocation.
set -euo pipefail

BRANCH="${SYNC_BRANCH:?SYNC_BRANCH is required}"
TARGET="${TARGET_BRANCH:?TARGET_BRANCH is required}"
SUMMARY_FILE="${SUMMARY_FILE:?SUMMARY_FILE is required}"
TITLE="chore: sync upstream AWS Solutions pack and AWS runtime data"

if [[ -z "$(git status --porcelain -- tfnag/data)" ]]; then
  echo "No upstream drift; nothing to push."
  exit 0
fi

git config user.email "noreply@github.com"
git config user.name "github-actions[bot]"
git checkout -B "$BRANCH"
git add tfnag/data
git commit -m "$TITLE" -m "Generated by the weekly upstream-sync workflow."
# The branch is regenerated from the target branch on every run, so the remote
# copy of a superseded sync is replaced rather than merged into.
git push --force origin "HEAD:refs/heads/$BRANCH"

existing="$(gh pr list --head "$BRANCH" --base "$TARGET" --state open \
  --json number --jq '.[0].number // empty')"

if [[ -n "$existing" ]]; then
  gh pr edit "$existing" --body-file "$SUMMARY_FILE" >/dev/null
  pr_id="$existing"
else
  gh pr create --head "$BRANCH" --base "$TARGET" \
    --title "$TITLE" --body-file "$SUMMARY_FILE" >/dev/null
  pr_id="$(gh pr list --head "$BRANCH" --base "$TARGET" --state open \
    --json number --jq '.[0].number')"
fi

pr_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/pull/${pr_id}"
echo "Sync PR: $pr_url"
{
  echo "prId=$pr_id"
  echo "prUrl=$pr_url"
} >> "$GITHUB_OUTPUT"
